
name: Build And Deploy Docs

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "develop" branch
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  release:
    types:
      - created

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      with:
          fetch-depth: 0
      # Runs a set of commands using the runners shell
      - name: Set system to non-interactive mode
        run: export DEBIAN_FRONTEND=noninteractive

      - name: Dependencies
        run: |
          pip install -U sphinx-rtd-theme pyyaml

      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd doc/sphinx
          sphinx-build -b html . ../public

      # Publish
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public          
          force_orphan: true
