
name: Build And Deploy Docs

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]
  release:
    types:
      - created
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set system to non-interactive mode
        run: export DEBIAN_FRONTEND=noninteractive
      - name: Dependencies
        run: |
          pip install -U sphinx-rtd-theme pyyaml
      - name: Build
        run: |
          cd ./doc
          sphinx-build -b html . ../public
      - name: Deploy
        if: ${{ github.event.pull_request.head.repo.full_name == github.repository }}
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public          
          force_orphan: true
